baseURL = "https://nombi.info/"
defaultContentLanguage = "ja"
title = "nombi.info"
theme = "m10c"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2

[params]
  author = "siubiang"
  description = "Electronic work notes, small trip photos, etc."
  menu_item_separator = " | "
  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://twitter.com/siubiang"
  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/siubiang"
  [params.style]
    darkestColor = "#242423"
    darkColor = "#333533"
    lightColor = "#cfdbd5"
    lightestColor = "#f2fdff"
    primaryColor = "#52bfdd"
